"""add incident analyses table

Revision ID: 49235e9ca726
Revises: 36e2984390b5
Create Date: 2026-03-05 05:07:42.435430
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49235e9ca726'
down_revision: Union[str, None] = '36e2984390b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Text(), nullable=False),
    sa.Column('contributing_factors', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['safety_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_analyses_id'), 'incident_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_incident_analyses_incident_id'), 'incident_analyses', ['incident_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_analyses_incident_id'), table_name='incident_analyses')
    op.drop_index(op.f('ix_incident_analyses_id'), table_name='incident_analyses')
    op.drop_table('incident_analyses')
    # ### end Alembic commands ###
